### PR TITLE
bug fix to make Dir listing working with MinIO

### PR DESCRIPTION
**Pull request by wyang007**

### CODE REVIEW

**Comment by wyang007** [comment]
Hi @mpatrascoiu or others, can you review this pull request ?

**Comment by wyang007** [comment]
Sorry for the delay - it has been quite a while since l last look at this. It turns out this is pull request only has half of what I changed. I will close this pull.

Line 119 to 121 ([link](https://github.com/cern-fts/davix/blob/d6df7e0483e954107e74e638183e6ad79f09ec80/src/xml/s3propparser.cpp#L119))
is indeed a bug (introduced by me, apologies) and need to be fixed. But there are more than one ways to fix it and I will use an e-mail thread to discuss that with you.

**Comment by wyang007** [comment]
See comment above

**Comment by mpatrascoiu** [comment]
Discussion carried and solved in #122

**Pull request closed without merging**
