### PR TITLE
Use sed in a more POSIX compliant way

### LINKED ISSUE #112: [FreeBSD] Davix build fails on FreeBSD
building on FreeBSD fails because BSD sed -i requires a prefix argument (it is optional in GNU sed)
PR follows

### PR DESCRIPTION
**Pull request by mkrzewic**
Fixes #112

### CODE REVIEW

**Comment by mpatrascoiu** [comment]
Thanks! I don't see the need for `gcc --> cc` change. 

Davix is officially supported on `gcc`. By changing it to `cc`, I don't want to raise hopes for other non-gcc compilers. Those are simply untested by us.

**Comment by mkrzewic** [comment]
removed the gcc->cc thing. it does seem to work fine with llvm though :)

**Comment by mkrzewic** [comment]
the problem I'm trying to solve is building as an automatic dependency of root on FreeBSD. gcc is not always there (can be installed, but it is a rather large dependency), llvm is the default. Davix and the rest can be built via the ports tree where these issues can be patched, but it would be nice if root could be built from source with as little effort as possible, just relying on roots own build system.

**Comment by mpatrascoiu** [comment]
Hello,

Yes, but we shouldn't change things in Davix to non-supported configurations just for the purpose of having Root build :slightly_smiling_face: 
I'm merging the `sed` change.

Thanks!

**Pull request merged**
